variables:
  DOCKER_REGISTRY: dr.cert.pl
  GIT_SUBMODULE_STRATEGY: none

services:
  - docker:dind

stages:
  - test
  - deploy

test:
  image: python:3.7
  stage: test
  script:
    - pip3 install -r requirements.txt
    - python -m unittest discover

deploy:
  image: certpl/deploy:0f008c7ef99242f98e743d0961a306b09b8376d5
  stage: deploy
  only:
  - master
  script:
  - docker login -u "$DOCKER_REGISTRY_LOGIN" -p "$DOCKER_REGISTRY_PASSWORD" https://dr.cert.pl
  - kubernetes_use_token https://kapi.cert.pl "$KUBE_TOKEN"
  - deploy production
