image: certpl/docker-ci-base

stages:
- deploy

services:
- docker:dind

deploy:
  stage: deploy
  only:
  - master
  script:
  - docker login -u "$DOCKER_REGISTRY_LOGIN" -p "$DOCKER_REGISTRY_PASSWORD" https://dr.cert.pl
  - kubernetes_use_token https://kapi.cert.pl "$KUBE_TOKEN"
  - deploy --production
